version: 2
updates:
- package-ecosystem: uv
  directories:
    - "/"
    - "/cronjobs"
    - "/git-reader"
    - "/browser-tests"
  schedule:
    interval: weekly
    day: sunday
    timezone: UCT
  allow:
    - dependency-type: "all"
  groups:
    production-dependency-patches:
      dependency-type: "production"
      update-types: ["patch"]
    development-dependencies:
      dependency-type: "development"
      update-types: ["major", "minor", "patch"]
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: UCT
  open-pull-requests-limit: 99
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  groups:
    all-dependencies:
      update-types: ["major", "minor", "patch"]
